name: wr
on:
  workflow_run:
    workflows: ["pr"]
    types:
      - completed

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      
